### ISSUE TITLE
Document if the is code is production ready

### ISSUE THREAD

**Issue by DemiMarie** [seL4/seL4_libs#14]
Is this code considered production ready?

My main interest in seL4 comes from potential use as a general purpose microhypervisor in highly dynamic systems.

**Comment by kent-mcleod** [comment]
Nope.  These libraries are provided as is, and have been developed for rapidly prototyping systems on seL4. They have not been through intensive testing or verification and do have bugs. They would potentially be a useful starting point for developing a dynamic hypervisor but it would be a non-negligible amount of work.
